export {default as Banner} from "./Banner"
export {default as KeyFeatures} from "./KeyFeatures"
export {default as Navbar} from "./Navbar"
export {default as AboutUs} from "./AboutUs"
export {default as Footer} from "./Footer"
export {default as OurTechStack} from "./OurTechStack"
export {default as OurTimeline} from "./OurTimeline"